COMP: Need to limit scope of variables in switch
This error occurs when a vairable declared inside
a switch statement is not explicitly limited to one case.

error: switch case is in protected scope

git-svn-id: https://advants.svn.sourceforge.net/svnroot/advants@1154 fd2da0a4-d968-48df-9cb5-d8c496287cbf